name: Oulun Paitapaino
favicon: null
layout_spectrum: 0.09453566535376012
typography_spectrum: 0.5212338920682669
title: Painatuksia jo vuodesta 1992
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.3703328378032893
  lightness: 0.20024058921262622
  saturation: 0.8298570506740361
  rhythmicContrast: 0.891045895172283
purpose: []
